include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v17.0.0-beta.28

Install:
  rules:
    - when: never

Lint:
  rules:
    - when: never

Test:
  rules:
    - when: never

Build:
  rules:
    - when: never

Review:
  rules:
    - when: never

Register image:
  extends: .autodevops_register_image
  needs: []
